name: Locust Load Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load environment variables
        run: |
          echo "Loading .env"
          export $(grep -v '^#' .env | xargs)

      - name: Run Locust headless test
        run: |
         mkdir -p reports
         python -m locust -f locustfile.py \
           --headless \
           -u ${USERS:-5} \
           -r ${SPAWN_RATE:-2} \
           --run-time ${RUN_TIME:-1m} \
           --host ${TARGET_URL:-https://example.com} \
           --html reports/locust_report.html \
           --csv reports/locust_stats

      - name: Upload Locust report
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: reports/
