name: Locust Load Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      # Run Locust test
      - name: Run Locust headless test
        env:
          LOCUST_USERNAME: ${{ secrets.LOCUST_USERNAME }}
          LOCUST_PASSWORD: ${{ secrets.LOCUST_PASSWORD }}
          LOCUST_DEVICE: ${{ secrets.LOCUST_DEVICE }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: |
          mkdir -p reports
          echo "✅ Environment variables loaded:"
          echo "  Username: $LOCUST_USERNAME"
          echo "  Device: $LOCUST_DEVICE"
          echo "  Target URL: $TARGET_URL"

          python -m locust -f locustfile.py \
            --headless \
            -u ${USERS:-5} \
            -r ${SPAWN_RATE:-2} \
            --run-time ${RUN_TIME:-1m} \
            --host ${TARGET_URL} \
            --html reports/locust_report.html \
            --csv reports/locust_stats

      # Upload test reports
      - name: Upload Locust report
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: reports/
